# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 28) do

  create_table "authors", :force => true do |t|
    t.column "created_at",  :datetime,                                   :null => false
    t.column "modified_at", :datetime,                                   :null => false
    t.column "email",       :string
    t.column "hashed_pass", :string,   :limit => 40
    t.column "name",        :string,   :limit => 100
    t.column "url",         :string
    t.column "is_active",   :boolean,                 :default => false
  end

  create_table "blacklist", :force => true do |t|
    t.column "item",       :string
    t.column "created_at", :datetime, :null => false
  end

  create_table "comments", :force => true do |t|
    t.column "post_id",         :integer
    t.column "name",            :string
    t.column "email",           :string
    t.column "url",             :string
    t.column "subject",         :string
    t.column "synd_title",      :string
    t.column "body",            :text
    t.column "body_raw",        :text
    t.column "body_searchable", :text
    t.column "ip",              :string
    t.column "is_approved",     :boolean,  :default => false
    t.column "created_at",      :datetime,                    :null => false
    t.column "modified_at",     :datetime,                    :null => false
  end

  create_table "pages", :force => true do |t|
    t.column "permalink",   :string,   :limit => 128
    t.column "body_raw",    :text
    t.column "body",        :text
    t.column "is_active",   :boolean,                 :default => true
    t.column "created_at",  :datetime
    t.column "modified_at", :datetime
    t.column "text_filter", :string
    t.column "title",       :string,   :limit => 128
  end

  create_table "posts", :force => true do |t|
    t.column "author_id",           :integer,                 :default => 0,    :null => false
    t.column "created_at",          :datetime,                                  :null => false
    t.column "modified_at",         :datetime,                                  :null => false
    t.column "permalink",           :string,   :limit => 128
    t.column "title",               :string
    t.column "synd_title",          :string
    t.column "summary",             :text
    t.column "body_raw",            :text
    t.column "extended_raw",        :text
    t.column "body",                :text
    t.column "extended",            :text
    t.column "is_active",           :boolean,                 :default => true
    t.column "custom_field_1",      :string
    t.column "custom_field_2",      :string
    t.column "custom_field_3",      :string
    t.column "body_searchable",     :text
    t.column "extended_searchable", :text
    t.column "text_filter",         :string
    t.column "comment_status",      :integer,                 :default => 0
  end

  create_table "preferences", :force => true do |t|
    t.column "nice_name",   :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
    t.column "name",        :string, :default => "", :null => false
    t.column "value",       :string, :default => "", :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string, :limit => 128
  end

  create_table "tags_posts", :id => false, :force => true do |t|
    t.column "tag_id",  :integer
    t.column "post_id", :integer
  end

  create_table "updates", :force => true do |t|
    t.column "last_checked_at",  :datetime
    t.column "update_available", :boolean,  :default => false
    t.column "update_version",   :string
  end

end
